### ISSUE TITLE
[feature request] need webhook validation for perserve-unknown fields like pod template

### ISSUE THREAD

**Issue by gotosre** [openkruise/kruise#1000] opened 2022-06-17 17:45 UTC
k8 ver: 1.18
kruise ver: 1.2.0

manifest:

```
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Delete
```

but when apply(create)

manifest become default value 
```
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain
```

when i edit it with kubectl edit

it become as expected

```
    spec:
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Delete
```

**Comment by gotosre** [comment] 2022-06-19 11:58
create/apply action doesnt work
patch works

**Comment by veophi** [comment] 2022-06-20 03:26
So sorry for that...

You can use `apps.kruise.io/v1beta1` instead of `apps.kruise.io/v1alpha1` in your **yaml configuration** to avoid this problem temporarily, and we will fix it later.

**Comment by FillZpp** [comment] 2022-06-20 03:31
> You can use `apps.kruise.io/v1beta1` instead of `apps.kruise.io/v1alpha1` in your **yaml configuration** to avoid this problem temporarily, and we will fix it later.

You sure it is because @gotosre is using `apps.kruise.io/v1alpha1`? If so, it is the expected behavior. The `v1alpha1` is deprecated and all new fields and features will only be supported in `v1beta1`.

**Comment by gotosre** [comment] 2022-06-20 03:44
sorry，my fault, i put there code snippet to template.spec not spec...
but why can template.spec set unknown field~ i think we can add some validation.
ty everyone, close it.

**Comment by FillZpp** [comment] 2022-06-20 03:49
> but why can template.spec set unknown field~ i think we can add some validation.

It is because the `template` field in CRD is marked as `x-kubernetes-preserve-unknown-fields`. But true, some validation for these fields in webhook should be added.

**Comment by FillZpp** [comment] 2022-06-20 04:00
/reopen
/retitle [feature request] need webhook validation for perserve-unknown fields like pod template

**Comment by FillZpp** [comment] 2022-06-20 04:02
/retitle [feature request] need webhook validation for perserve-unknown fields like pod template

**Closed** 2022-09-26 20:34 UTC
Labels: kind/bug, wontfix
